Add support for graph.RO_QUERY command
RedisGraph/JRedisGraph pull request #105
Opened 2021-01-21 22:44 UTC by filipecosta90

This PR kicks off the support for graph.RO_QUERY command by introducing queryReadOnly(). It includes the same api methods that query() offers.

2021-01-23 21:17 UTC, DvirDukhan requested changes
@filipecosta90 
1. see comments
2. please add the RO API also to the transactions 
3. I think that we need dedicated test functions for RO API instead of mixing with the current tests, which are messy

2021-01-23 21:17 UTC, DvirDukhan commented on src/main/java/com/redislabs/redisgraph/RedisGraph.java
> +
remove this as this is deprecated API

2021-01-23 21:17 UTC, DvirDukhan commented on src/main/java/com/redislabs/redisgraph/impl/api/AbstractRedisGraph.java
> +
deprecated

2021-01-23 21:17 UTC, DvirDukhan commented on src/main/java/com/redislabs/redisgraph/RedisGraph.java
> +    ResultSet queryReadOnly(String graphId, String query);
```suggestion
    ResultSet readOnlyQuery(String graphId, String query);
```

2021-01-23 21:17 UTC, DvirDukhan commented on src/main/java/com/redislabs/redisgraph/RedisGraph.java
> +    ResultSet queryReadOnly(String graphId, String query, long timeout);
```suggestion
    ResultSet readOnlyQuery(String graphId, String query, long timeout);
```

2021-01-23 21:17 UTC, DvirDukhan commented on src/main/java/com/redislabs/redisgraph/RedisGraph.java
> +    ResultSet queryReadOnly(String graphId, String query, Map<String, Object> params);
```suggestion
    ResultSet readOnlyQuery(String graphId, String query, Map<String, Object> params);
```

2021-01-23 21:17 UTC, DvirDukhan commented on src/main/java/com/redislabs/redisgraph/RedisGraph.java
> +    ResultSet queryReadOnly(String graphId, String query, Map<String, Object> params, long timeout);
```suggestion
    ResultSet readOnlyQuery(String graphId, String query, Map<String, Object> params, long timeout);
```

2021-01-24 16:30 UTC, filipecosta90 commented on src/main/java/com/redislabs/redisgraph/impl/api/AbstractRedisGraph.java
> +
fixed in the latest commit

2021-02-28 13:38 UTC, sazzad16 approved these changes

2021-04-08 07:53 UTC, tanvirp commented
Will RO api work with read only slaves? Looks like https://github.com/RedisGraph/JRedisGraph/blob/ed0c37c6708709ec0a27140897ac1a496b586010/src/main/java/com/redislabs/redisgraph/impl/graph_cache/GraphCacheList.java#L53 will eventually call https://github.com/RedisGraph/JRedisGraph/blob/ed0c37c6708709ec0a27140897ac1a496b586010/src/main/java/com/redislabs/redisgraph/impl/api/AbstractRedisGraph.java#L112, which will issue the `QUERY` command instead of `RO_QUERY` command. I am not sure if this will be taken care in this PR.

2021-04-11 10:34 UTC, sazzad16 approved these changes

2021-04-11 10:38 UTC, sazzad16 requested changes

2021-04-11 10:38 UTC, sazzad16 commented on src/main/java/com/redislabs/redisgraph/impl/api/ContextedRedisGraph.java
> +        }
Two of these error classes were removed. Now there is only `JRedisGraphException`.

2021-04-21 11:35 UTC, sazzad16 approved these changes

2021-04-21 11:39 UTC, sazzad16 commented
@tanvirp Do you have a solution in mind? Feel free to craft a PR.

2021-04-21 14:09 UTC, gkorland approved these changes

2021-04-21 14:11 UTC, merged