initial commit of Pipeline support
RedisGraph/JRedisGraph pull request #123
Opened 2021-07-19 18:47 UTC by gkorland

2021-07-19 21:14 UTC, DvirDukhan requested changes

2021-07-19 21:14 UTC, DvirDukhan commented on src/main/java/com/redislabs/redisgraph/RedisGraphPipeline.java
> +     * get return values from pipelined commands, capture the different Response&lt;?&gt; of the
format of `Response&lt;?&gt;`

2021-07-19 21:14 UTC, DvirDukhan commented on src/main/java/com/redislabs/redisgraph/impl/api/RedisGraphPipeline.java
> +        client.sendCommand(RedisGraphCommand.QUERY, graphId, query, "--COMPACT");
don't we have a static string for `--COMPACT`?

2021-07-19 21:14 UTC, DvirDukhan commented on src/main/java/com/redislabs/redisgraph/impl/api/RedisGraphPipeline.java
> +        client.sendCommand(RedisGraphCommand.QUERY, graphId, query, "--COMPACT", "TIMEOUT", Long.toString(timeout));
don't we have static strings for compact and timeout?

2021-07-19 21:14 UTC, DvirDukhan commented on src/test/java/com/redislabs/redisgraph/PipelineTest.java
> +    public void testCreateNode() {
not relevant here

2021-07-19 21:14 UTC, DvirDukhan commented on src/test/java/com/redislabs/redisgraph/PipelineTest.java
> +    public void testCreateLabeledNode() {
not relevant here

2021-07-19 21:14 UTC, DvirDukhan commented on src/test/java/com/redislabs/redisgraph/PipelineTest.java
> +    public void testConnectNodes() {
not relevant here

2021-07-19 21:14 UTC, DvirDukhan commented on src/test/java/com/redislabs/redisgraph/PipelineTest.java
> +    public void testDeleteNodes(){
not relevant here

2021-07-19 21:14 UTC, DvirDukhan commented on src/test/java/com/redislabs/redisgraph/PipelineTest.java
> +    public void testDeleteRelationship(){
not relevant here

2021-07-19 21:14 UTC, DvirDukhan commented on src/test/java/com/redislabs/redisgraph/PipelineTest.java
> +    public void testIndex() {
not relevant here

2021-07-19 21:14 UTC, DvirDukhan commented on src/test/java/com/redislabs/redisgraph/PipelineTest.java
> +    public void testHeader(){
not relevant here

2021-07-19 21:14 UTC, DvirDukhan commented on src/test/java/com/redislabs/redisgraph/PipelineTest.java
> +    public void testRecord(){
not relevant here

2021-07-19 21:14 UTC, DvirDukhan commented on src/test/java/com/redislabs/redisgraph/PipelineTest.java
> +    public void tinyTestMultiThread(){
not relevant here

2021-07-19 21:14 UTC, DvirDukhan commented on src/test/java/com/redislabs/redisgraph/PipelineTest.java
> +    public void testMultiThread(){
not relevant here

2021-07-19 21:14 UTC, DvirDukhan commented on src/test/java/com/redislabs/redisgraph/PipelineTest.java
> +    public void testAdditionToProcedures(){
not relevant here

2021-07-19 21:14 UTC, DvirDukhan commented on src/test/java/com/redislabs/redisgraph/PipelineTest.java
> +    public void testEscapedQuery() {
not relevant here

2021-07-19 21:14 UTC, DvirDukhan commented on src/test/java/com/redislabs/redisgraph/PipelineTest.java
> +    public void testMultiExecWithReadOnlyQueries(){
```suggestion
    public void testPipelineWithReadOnlyQueries(){
```

2021-07-20 11:10 UTC, gkorland commented on src/main/java/com/redislabs/redisgraph/RedisGraphPipeline.java
> +     * get return values from pipelined commands, capture the different Response&lt;?&gt; of the
`Response<?>`

2021-07-20 11:46 UTC, DvirDukhan approved these changes

2021-07-20 13:13 UTC, merged