Adds Jedis constructor, general cleanup
RedisGraph/JRedisGraph pull request #135
Opened 2021-11-14 17:56 UTC by bsbodden

* Adds Jedis instance constructor + tests
* Removes all unused imports
* Fixed all deprecation warning
* Updates JUnit 4 to latest release

2022-01-08 04:48 UTC, sazzad16 requested changes
Please replace the tab characters with spaces.

2022-01-08 05:09 UTC, sazzad16 requested changes

2022-01-08 05:09 UTC, sazzad16 commented on src/main/java/com/redislabs/redisgraph/impl/api/RedisGraph.java
> +	}
```suggestion
    public void close() {
        if (pool != null) {
            pool.close();
        }
        if (jedis != null) {
            jedis.close();
        }
    }
```

2022-01-08 05:09 UTC, sazzad16 commented on src/main/java/com/redislabs/redisgraph/impl/api/RedisGraphPipeline.java
> +			@Override
```suggestion
            @SuppressWarnings("unchecked")
            @Override
```

2022-01-08 05:09 UTC, sazzad16 commented on src/main/java/com/redislabs/redisgraph/impl/api/RedisGraphPipeline.java
> +			@Override
```suggestion
            @SuppressWarnings("unchecked")
            @Override
```

2022-01-08 05:09 UTC, sazzad16 commented on src/main/java/com/redislabs/redisgraph/impl/api/RedisGraphPipeline.java
> +			@Override
```suggestion
            @SuppressWarnings("unchecked")
            @Override
```

2022-01-08 05:09 UTC, sazzad16 commented on src/main/java/com/redislabs/redisgraph/impl/api/RedisGraphPipeline.java
> +			@Override
```suggestion
            @SuppressWarnings("unchecked")
            @Override
```

2022-01-08 05:09 UTC, sazzad16 commented on src/main/java/com/redislabs/redisgraph/impl/api/RedisGraphPipeline.java
> +			@Override
```suggestion
            @SuppressWarnings("unchecked")
            @Override
```

2022-01-08 05:09 UTC, sazzad16 commented on src/main/java/com/redislabs/redisgraph/impl/api/RedisGraphPipeline.java
> +			@Override
```suggestion
            @SuppressWarnings("unchecked")
            @Override
```

2022-01-08 05:09 UTC, sazzad16 commented on src/main/java/com/redislabs/redisgraph/impl/api/RedisGraphPipeline.java
> +			@Override
```suggestion
            @SuppressWarnings("unchecked")
            @Override
```

2022-01-08 05:09 UTC, sazzad16 commented on src/main/java/com/redislabs/redisgraph/impl/api/RedisGraphPipeline.java
> +			@Override
```suggestion
            @SuppressWarnings("unchecked")
            @Override
```

2022-01-08 05:09 UTC, sazzad16 commented on src/test/java/com/redislabs/redisgraph/exceptions/JRedisGraphErrorTest.java
> +            assertTrue(exception.getMessage().contains("Type mismatch: expected String but was Integer"));
```suggestion
        JRedisGraphException exception = assertThrows(JRedisGraphException.class,
                () -> api.query("social", "RETURN toUpper(5)"));
            assertTrue(exception.getMessage().contains("Type mismatch: expected String but was Integer"));
```

2022-01-08 05:09 UTC, sazzad16 commented on src/test/java/com/redislabs/redisgraph/exceptions/JRedisGraphErrorTest.java
> +            assertTrue(exception.getMessage().contains("Type mismatch: expected String but was Integer"));
```suggestion
        JRedisGraphException exception = assertThrows(JRedisGraphException.class,
                () -> api.query("social", "MATCH (p:person) RETURN toUpper(p.mixed_prop)"));
            assertTrue(exception.getMessage().contains("Type mismatch: expected String but was Integer"));
```

2022-01-08 05:09 UTC, sazzad16 commented on src/test/java/com/redislabs/redisgraph/exceptions/JRedisGraphErrorTest.java
> +            assertTrue(exception.getMessage().contains("Type mismatch: expected String but was Integer"));
```suggestion
        JRedisGraphException exception = assertThrows(JRedisGraphException.class,
                () -> c.query("social", "RETURN toUpper(5)"));
            assertTrue(exception.getMessage().contains("Type mismatch: expected String but was Integer"));
```

2022-01-08 05:09 UTC, sazzad16 commented on src/test/java/com/redislabs/redisgraph/exceptions/JRedisGraphErrorTest.java
> +            assertTrue(exception.getMessage().contains("Missing parameters"));
```suggestion
        JRedisGraphException exception = assertThrows(JRedisGraphException.class,
                () -> api.query("social", "RETURN $param"));
            assertTrue(exception.getMessage().contains("Missing parameters"));
```

2022-01-08 05:09 UTC, sazzad16 commented on src/test/java/com/redislabs/redisgraph/exceptions/JRedisGraphErrorTest.java
> +            assertTrue(exception.getMessage().contains("Missing parameters"));
```suggestion
        JRedisGraphException exception = assertThrows(JRedisGraphException.class,
                () -> api.query("social", "RETURN $param", new HashMap<>()));
            assertTrue(exception.getMessage().contains("Missing parameters"));
```

2022-01-08 05:09 UTC, sazzad16 commented on src/test/java/com/redislabs/redisgraph/exceptions/JRedisGraphErrorTest.java
> +            assertTrue(exception.getMessage().contains("Type mismatch: expected String but was Integer"));
```suggestion

        JRedisGraphException exception = assertThrows(JRedisGraphException.class,
                () -> c.query("social", "MATCH (p:person) RETURN toUpper(p.mixed_prop)"));
            assertTrue(exception.getMessage().contains("Type mismatch: expected String but was Integer"));
```

2022-01-08 05:09 UTC, sazzad16 commented on src/test/java/com/redislabs/redisgraph/exceptions/JRedisGraphErrorTest.java
> +            assertTrue(exception.getMessage().contains("Query timed out"));
```suggestion
    public void timeoutException() {
        JRedisGraphException exception = assertThrows(JRedisGraphException.class,
                () -> api.query("social", "UNWIND range(0,100000) AS x WITH x AS x WHERE x = 10000 RETURN x", 1L));
            assertTrue(exception.getMessage().contains("Query timed out"));
```

2022-01-08 05:14 UTC, sazzad16 commented on src/main/java/com/redislabs/redisgraph/impl/api/RedisGraph.java
> +      return jedis != null ? jedis : pool.getResource();
```suggestion
        return jedis != null ? jedis : pool.getResource();
```

2022-01-09 18:26 UTC, bsbodden commented
> Please replace the tab characters with spaces.

Done. Thanks.

2022-01-10 06:57 UTC, sazzad16 approved these changes

2022-01-10 08:37 UTC, merged